export const REVIEW_REQUEST='REVIEW_REQUEST'
export const REVIEW_SUCCESS='REVIEW_SUCCESS'
export const REVIEW_FAILURE='REVIEW_FAILURE'

export const FIND_REVIEW_REQUEST='FIND_REVIEW_REQUEST'
export const FIND_REVIEW_SUCCESS='FIND_REVIEW_SUCCESS'
export const FIND_REVIEW_FAILURE='FIND_REVIEW_FAILURE'